// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-04-13 11:10:40.046022 +0800 CST m=+0.124224805

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "An example of gin",
        "title": "Golang Gin API",
        "termsOfService": "127.0.0.1:6001",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "127.0.0.1:6001"
        },
        "version": "1.0"
    },
    "basePath": "/v1",
    "paths": {
        "/secret/{access_key}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "获取S",
                "parameters": [
                    {
                        "type": "string",
                        "description": "秘钥KEY",
                        "name": "access_key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\": 1,\"message\": \"\",\"result\": {\"access_key\": \"xxx\",\"access_secret\": \"\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
